version: 0.2

env:
  variables:
    ACCOUNT_ID: ACCOUNT_ID
    key: "value"
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo build Docker image on `date`
      - docker build -t $ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/toy-robot:latest .
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push $ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/toy-robot:latest
      - printf '[{"name":"toy-robot","imageUri":$ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/toy-robot:latest}]' > imagedefinitions.json

  artifacts:
    files: imagedefinitions.json