version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region us-east-1)
  build:
    commands:
      - echo build Docker image on `date`
      - docker build -t 208157287953.dkr.ecr.us-east-1.amazonaws.com/toy-robot:latest .
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push 208157287953.dkr.ecr.us-east-1.amazonaws.com/toy-robot:latest